import type { BuildProject } from "@/lib/db";

export const APP_FUNNEL_CATALOG: Array<Omit<BuildProject, "id">> = [
  {
    name: "GearUpToFit Shoe Finder",
    productName: "RunMatch / Shoe Finder",
    platform: "other",
    projectUrl: "https://github.com/douphealth/runmatch-ai-buddy-1282c193",
    deployedUrl: "https://runmatch.gearup-flow-master.pages.dev/",
    description: "Running-shoe matching app for GearUpToFit, connected to the site's shoe-finder funnel.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Validate canonical production route, conversion tracking, affiliate monetization, and the WordPress-to-app funnel.",
    githubRepo: "https://github.com/douphealth/runmatch-ai-buddy-1282c193",
    parentWebsite: "https://gearuptofit.com/",
    landingPage: "https://gearuptofit.com/shoe-finder/",
    alternateUrls: ["https://shoe-match.gearuptofit.com/"],
    priority: "critical",
    importance: 100,
    portfolioGroup: "growth-app",
  },
  {
    name: "GearUpToFit Fitness Plan",
    productName: "Body Recomp OS / Fitness Plan",
    platform: "other",
    projectUrl: "https://github.com/douphealth/body-recomp-os-guru-7c1356da",
    deployedUrl: "https://fitness-plan.gearup-flow-master.pages.dev/",
    description: "Fitness-plan application for GearUpToFit, routed from the WordPress fitness-plan funnel.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Validate canonical production domain, Stripe/conversion tracking, and the WordPress landing-page handoff.",
    githubRepo: "https://github.com/douphealth/body-recomp-os-guru-7c1356da",
    parentWebsite: "https://gearuptofit.com/",
    landingPage: "https://gearuptofit.com/fitness-plan/",
    alternateUrls: ["https://fitness-plan.gearuptofit.com/"],
    priority: "critical",
    importance: 99,
    portfolioGroup: "growth-app",
  },
  {
    name: "Frenchie Care Compass",
    productName: "Frenchie Care Plan",
    platform: "other",
    projectUrl: "https://github.com/douphealth/frenchie-care-compass",
    deployedUrl: "https://care-plan.frenchyfab.com/",
    description: "French Bulldog care-plan application connected to FrenchyFab.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Verify paid conversion flow, tracking, and contextual placement on high-intent FrenchyFab pages.",
    githubRepo: "https://github.com/douphealth/frenchie-care-compass",
    parentWebsite: "https://frenchyfab.com/",
    landingPage: "https://frenchyfab.com/",
    alternateUrls: [],
    priority: "high",
    importance: 95,
    portfolioGroup: "growth-app",
  },
  {
    name: "Mystic Blueprint Maker",
    productName: "Life Path",
    platform: "other",
    projectUrl: "https://github.com/douphealth/mystic-blueprint-maker",
    deployedUrl: "https://life-path.mysticaldigits.com/",
    description: "Life-path / numerology app connected to Mystical Digits.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Tighten website-to-app routing, conversion measurement, and monetization on high-intent numerology pages.",
    githubRepo: "https://github.com/douphealth/mystic-blueprint-maker",
    parentWebsite: "https://mysticaldigits.com/",
    landingPage: "https://mysticaldigits.com/",
    alternateUrls: [],
    priority: "high",
    importance: 94,
    portfolioGroup: "growth-app",
  },
  {
    name: "Mice Solver Pro",
    productName: "Mice Elimination",
    platform: "other",
    projectUrl: "https://github.com/douphealth/mice-solver-pro",
    deployedUrl: "https://elimination.micegoneguide.com/",
    description: "Mice-elimination application connected to Mice Gone Guide.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Remove fragile persistence dependencies, verify paid flow, and integrate the app into the site's highest-intent pages.",
    githubRepo: "https://github.com/douphealth/mice-solver-pro",
    parentWebsite: "https://micegoneguide.com/",
    landingPage: "https://micegoneguide.com/",
    alternateUrls: [],
    priority: "high",
    importance: 93,
    portfolioGroup: "growth-app",
  },
  {
    name: "Grow Stack Engine",
    productName: "Grow Plan",
    platform: "other",
    projectUrl: "https://github.com/douphealth/grow-stack-engine-945df4aa",
    deployedUrl: "https://grow-plan.gearuptogrow.com/",
    description: "Growth-plan application connected to GearUpToGrow.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Confirm canonical production use, measurement, and the most valuable site-to-app funnel.",
    githubRepo: "https://github.com/douphealth/grow-stack-engine-945df4aa",
    parentWebsite: "https://gearuptogrow.com/",
    landingPage: "https://gearuptogrow.com/",
    alternateUrls: [],
    priority: "high",
    importance: 90,
    portfolioGroup: "growth-app",
  },
  {
    name: "Plantastic Haven Pro",
    productName: "Pro Care",
    platform: "other",
    projectUrl: "https://github.com/douphealth/plantastic-haven-pro-8e23ae56",
    deployedUrl: "https://procare.plantastichaven.com/",
    description: "Plant-care application connected to Plantastic Haven.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Connect the app to high-intent plant-care pages and measure conversion from organic traffic.",
    githubRepo: "https://github.com/douphealth/plantastic-haven-pro-8e23ae56",
    parentWebsite: "https://plantastichaven.com/",
    landingPage: "https://plantastichaven.com/",
    alternateUrls: [],
    priority: "high",
    importance: 89,
    portfolioGroup: "growth-app",
  },
  {
    name: "Neural Prompt Coach",
    productName: "PromptGrade",
    platform: "other",
    projectUrl: "https://github.com/douphealth/neural-prompt-coach",
    deployedUrl: "",
    description: "Prompt evaluation/coaching application branded as PromptGrade.",
    techStack: [],
    status: "testing",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Confirm the canonical production URL, target site/funnel, monetization model, and analytics before promotion.",
    githubRepo: "https://github.com/douphealth/neural-prompt-coach",
    parentWebsite: "https://efficientgptprompts.com/",
    landingPage: "https://efficientgptprompts.com/",
    alternateUrls: [],
    priority: "medium",
    importance: 78,
    portfolioGroup: "tool",
  },
  {
    name: "Form Beauty Studio",
    productName: "ImageAlchemy",
    platform: "other",
    projectUrl: "https://github.com/douphealth/form-beauty-studio",
    deployedUrl: "https://imagealchemy.app/",
    description: "Image-generation/form-beautification application branded as ImageAlchemy.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Confirm production conversion path, pricing/monetization, analytics, and canonical repository/domain alignment.",
    githubRepo: "https://github.com/douphealth/form-beauty-studio",
    parentWebsite: "https://imagealchemy.app/",
    landingPage: "https://imagealchemy.app/",
    alternateUrls: [],
    priority: "medium",
    importance: 77,
    portfolioGroup: "tool",
  },
  {
    name: "Claw Skills Hub",
    productName: "OpenClaw Skills Hub",
    platform: "other",
    projectUrl: "https://github.com/douphealth/claw-skills-hub",
    deployedUrl: "https://openclaw-skillshub.com/",
    description: "OpenClaw skills discovery hub with a Cloudflare Pages deployment.",
    techStack: [],
    status: "deployed",
    startedDate: "2026-01-01",
    lastWorkedOn: "2026-09-28",
    nextSteps: "Confirm the canonical public domain, consolidate duplicate hub variants, and improve indexation/content architecture.",
    githubRepo: "https://github.com/douphealth/claw-skills-hub",
    parentWebsite: "https://openclaw-skillshub.com/",
    landingPage: "https://openclaw-skillshub.com/",
    alternateUrls: ["https://claw-skills-hub.pages.dev/"],
    priority: "medium",
    importance: 75,
    portfolioGroup: "tool",
  },
];
