import type { LucideIcon } from "lucide-react";
import {
  Home,
  Crosshair,
  CheckSquare,
  Calendar,
  RefreshCcw,
  Scale,
  Globe,
  Search,
  Github,
  Hammer,
  Zap,
  DollarSign,
  FileText,
  Lightbulb,
  Bell,
  PanelsTopLeft,
  Flame,
  Link2,
  KeyRound,
  Radar,
  Cloud,
  Rocket,
  Bug,
  Timer,
  Newspaper,
  AtSign,
  Users,
} from "lucide-react";

export type MissionNavGroup = "operate" | "grow" | "manage" | "systems";

export interface MissionNavItem {
  id: string;
  label: string;
  shortLabel?: string;
  description: string;
  group: MissionNavGroup;
  icon: LucideIcon;
  emoji: string;
  keywords: string[];
  rank: number;
}

export const MISSION_NAV: MissionNavItem[] = [
  {
    id: "dashboard",
    label: "Command Deck",
    shortLabel: "Home",
    description: "Decide what matters now and execute the day.",
    group: "operate",
    icon: Home,
    emoji: "⌂",
    keywords: ["home", "dashboard", "today", "overview", "command"],
    rank: 100,
  },
  {
    id: "now",
    label: "Today",
    description: "The shortest path through today's commitments.",
    group: "operate",
    icon: Crosshair,
    emoji: "◎",
    keywords: ["now", "today", "next", "priority"],
    rank: 99,
  },
  {
    id: "tasks",
    label: "Tasks",
    description: "Capture, prioritize, schedule and complete work.",
    group: "operate",
    icon: CheckSquare,
    emoji: "✓",
    keywords: ["todo", "work", "actions", "inbox"],
    rank: 98,
  },
  {
    id: "calendar",
    label: "Calendar",
    description: "Time blocks, events and real capacity.",
    group: "operate",
    icon: Calendar,
    emoji: "□",
    keywords: ["date", "schedule", "events", "time"],
    rank: 97,
  },
  {
    id: "review",
    label: "Review",
    description: "Close loops and keep the system trustworthy.",
    group: "operate",
    icon: RefreshCcw,
    emoji: "↻",
    keywords: ["review", "weekly", "cleanup", "close loops"],
    rank: 90,
  },
  {
    id: "decisions",
    label: "Decisions",
    description: "Findings, decisions and unresolved questions.",
    group: "operate",
    icon: Scale,
    emoji: "⚖",
    keywords: ["findings", "decision", "choice", "evidence"],
    rank: 88,
  },
  {
    id: "websites",
    label: "Websites",
    description: "Portfolio health, operations and monetization.",
    group: "grow",
    icon: Globe,
    emoji: "◉",
    keywords: ["sites", "domains", "wordpress", "portfolio"],
    rank: 95,
  },
  {
    id: "seo",
    label: "Search Growth",
    shortLabel: "SEO",
    description: "SEO, GEO, AEO, indexing and visibility.",
    group: "grow",
    icon: Search,
    emoji: "⌕",
    keywords: ["seo", "geo", "aeo", "search", "gsc", "ranking"],
    rank: 94,
  },
  {
    id: "github",
    label: "GitHub",
    description: "All repositories ordered by portfolio importance.",
    group: "grow",
    icon: Github,
    emoji: "◈",
    keywords: ["repo", "code", "git", "project"],
    rank: 93,
  },
  {
    id: "builds",
    label: "Builds",
    description: "Apps, deployments and product builds.",
    group: "grow",
    icon: Hammer,
    emoji: "◇",
    keywords: ["app", "build", "lovable", "deploy", "product"],
    rank: 92,
  },
  {
    id: "wp-manage",
    label: "WordPress",
    description: "WordPress operations and publishing controls.",
    group: "grow",
    icon: Zap,
    emoji: "W",
    keywords: ["wordpress", "posts", "pages", "publish"],
    rank: 91,
  },
  {
    id: "industry",
    label: "Trends",
    description: "Industry changes worth acting on.",
    group: "grow",
    icon: Newspaper,
    emoji: "↗",
    keywords: ["news", "trends", "industry"],
    rank: 70,
  },
  {
    id: "mentions",
    label: "Mentions",
    description: "Brand and portfolio mentions.",
    group: "grow",
    icon: AtSign,
    emoji: "@",
    keywords: ["mentions", "brand", "citations"],
    rank: 69,
  },
  {
    id: "audience",
    label: "Audience",
    description: "Audience accounts and readings.",
    group: "grow",
    icon: Users,
    emoji: "◎",
    keywords: ["audience", "social", "followers"],
    rank: 68,
  },
  {
    id: "notes",
    label: "Notes",
    description: "Fast notes and working memory.",
    group: "manage",
    icon: FileText,
    emoji: "✎",
    keywords: ["notes", "memo", "write"],
    rank: 86,
  },
  {
    id: "projects",
    label: "Projects",
    description: "Project-level work and progress.",
    group: "manage",
    icon: PanelsTopLeft,
    emoji: "▦",
    keywords: ["projects", "kanban", "board"],
    rank: 85,
  },
  {
    id: "payments",
    label: "Finance",
    description: "Payments, obligations and money flow.",
    group: "manage",
    icon: DollarSign,
    emoji: "$",
    keywords: ["finance", "payments", "invoice", "money"],
    rank: 84,
  },
  {
    id: "ideas",
    label: "Ideas",
    description: "Ideas worth keeping, testing or killing.",
    group: "manage",
    icon: Lightbulb,
    emoji: "✦",
    keywords: ["ideas", "brainstorm", "opportunities"],
    rank: 75,
  },
  {
    id: "reminders",
    label: "Reminders",
    description: "Time-sensitive follow-ups and obligations.",
    group: "manage",
    icon: Bell,
    emoji: "!",
    keywords: ["reminder", "follow up", "deadline"],
    rank: 74,
  },
  {
    id: "habits",
    label: "Habits",
    description: "Recurring personal routines and streaks.",
    group: "manage",
    icon: Flame,
    emoji: "◆",
    keywords: ["habits", "routine", "streak"],
    rank: 60,
  },
  {
    id: "links",
    label: "Links",
    description: "Saved references and useful destinations.",
    group: "manage",
    icon: Link2,
    emoji: "↗",
    keywords: ["links", "bookmarks", "resources"],
    rank: 55,
  },
  {
    id: "control-center",
    label: "Captures",
    description: "Captured inputs waiting for triage.",
    group: "systems",
    icon: Radar,
    emoji: "◌",
    keywords: ["capture", "inbox", "intake", "triage"],
    rank: 83,
  },
  {
    id: "google-tasks",
    label: "Google Tasks",
    description: "Google Tasks integration.",
    group: "systems",
    icon: CheckSquare,
    emoji: "G",
    keywords: ["google", "tasks", "sync"],
    rank: 52,
  },
  {
    id: "cloudflare",
    label: "Cloudflare",
    description: "Cloudflare deployment and infrastructure.",
    group: "systems",
    icon: Cloud,
    emoji: "☁",
    keywords: ["cloudflare", "pages", "dns", "cdn"],
    rank: 51,
  },
  {
    id: "vercel",
    label: "Vercel",
    description: "Vercel deployments and projects.",
    group: "systems",
    icon: Rocket,
    emoji: "▲",
    keywords: ["vercel", "deploy", "hosting"],
    rank: 50,
  },
  {
    id: "openclaw",
    label: "OpenClaw",
    description: "OpenClaw tools and automation.",
    group: "systems",
    icon: Bug,
    emoji: "◫",
    keywords: ["openclaw", "agent", "automation"],
    rank: 49,
  },
  {
    id: "credentials",
    label: "Credentials",
    description: "Credential references and access metadata.",
    group: "systems",
    icon: KeyRound,
    emoji: "⌘",
    keywords: ["credentials", "vault", "keys", "access"],
    rank: 48,
  },
  {
    id: "focus",
    label: "Focus",
    description: "Dedicated focus timer.",
    group: "systems",
    icon: Timer,
    emoji: "◷",
    keywords: ["focus", "timer", "pomodoro"],
    rank: 47,
  },
  {
    id: "settings",
    label: "Settings",
    description: "Mission Control preferences and connections.",
    group: "systems",
    icon: Zap,
    emoji: "⚙",
    keywords: ["settings", "preferences", "config"],
    rank: 40,
  },
];

export const MISSION_NAV_BY_ID = new Map(MISSION_NAV.map((item) => [item.id, item]));

export const PRIMARY_NAV_IDS = ["dashboard", "now", "tasks", "calendar"] as const;
export const GROW_NAV_IDS = ["websites", "seo", "github", "builds"] as const;

export const NAV_GROUP_LABELS: Record<MissionNavGroup, string> = {
  operate: "Operate",
  grow: "Grow",
  manage: "Manage",
  systems: "Systems",
};

export function missionNavItems(ids: readonly string[]) {
  return ids
    .map((id) => MISSION_NAV_BY_ID.get(id))
    .filter((item): item is MissionNavItem => Boolean(item));
}
