import type { GitHubRepo } from "@/lib/db";

export const GITHUB_REPO_CATALOG_GENERATED_AT = "2026-09-28";
export const GITHUB_REPO_CATALOG_COUNT = 81;

/**
 * Snapshot of every repository currently available to the connected douphealth
 * GitHub account. Existing user-edited repo records are never overwritten;
 * GitHubPage only inserts missing entries.
 */
export const GITHUB_REPO_CATALOG: Array<Omit<GitHubRepo, "id">> = [
  {
    "name": "mission-control-21072026",
    "url": "https://github.com/douphealth/mission-control-21072026",
    "description": "Primary Mission Control dashboard for personal, business, website, automation, and project operations.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://mission-control-21072026.pages.dev/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "critical",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "critical",
    "importance": 100,
    "doneSummary": "Current Mission Control codebase is connected; the app already includes task, website, GitHub, notes, capture, calendar, SEO, finance and control-center modules.",
    "pendingSummary": "Validate this upgrade branch, then merge/deploy after approval. Keep the repo catalog, notes editor, and mobile controls regression-tested.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 3296
  },
  {
    "name": "gearuptofit",
    "url": "https://github.com/douphealth/gearuptofit",
    "description": "Primary GearUpToFit website repository and recovery/growth asset.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://gearuptofit.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "critical"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "critical",
    "importance": 99,
    "doneSummary": "Primary site repository is connected and tracked as the highest-value website recovery project.",
    "pendingSummary": "Continue indexation recovery, restore historically valuable URLs, resolve canonical/sitemap/status-code issues, then optimize high-impression pages and monetization.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1669
  },
  {
    "name": "affiliatemarketingforsuccess",
    "url": "https://github.com/douphealth/affiliatemarketingforsuccess",
    "description": "Affiliate Marketing for Success website repository and monetization asset.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://affiliatemarketingforsuccess.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "critical"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "critical",
    "importance": 97,
    "doneSummary": "Site repository is connected; analytics/affiliate-click work and content/monetization infrastructure already exist.",
    "pendingSummary": "Finish review-post monetization coverage, merchant/affiliate links, product boxes, and underperforming SEO pages.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 2164
  },
  {
    "name": "alexios-hermes-control-plane",
    "url": "https://github.com/douphealth/alexios-hermes-control-plane",
    "description": "Control plane for Hermes/Astra/Jev automation workflows.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "critical"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "critical",
    "importance": 96,
    "doneSummary": "Control-plane repository exists and is connected to the current automation stack.",
    "pendingSummary": "Confirm the single canonical live control plane, remove obsolete bot/process paths, and keep execution observable and reversible.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 297
  },
  {
    "name": "hermes-agent",
    "url": "https://github.com/douphealth/hermes-agent",
    "description": "Hermes agent codebase used by the automation stack.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "critical"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "critical",
    "importance": 95,
    "doneSummary": "Hermes agent source repository exists and is connected.",
    "pendingSummary": "Confirm the exact live revision used on the VPS and remove/disable superseded Telegram/WordPress automation paths.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 323990
  },
  {
    "name": "hermes-config-001",
    "url": "https://github.com/douphealth/hermes-config-001",
    "description": "Private Hermes configuration repository for live automation setup.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "critical",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "critical",
    "importance": 94,
    "doneSummary": "Private live configuration repository exists and is connected.",
    "pendingSummary": "Reconcile live VPS configuration with this repo and remove stale/duplicate bot profiles and credentials references.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 18846
  },
  {
    "name": "growthscribe-os",
    "url": "https://github.com/douphealth/growthscribe-os",
    "description": "SEO/GEO/AEO growth automation and website operations repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "critical"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "critical",
    "importance": 93,
    "doneSummary": "Growth/SEO automation repository exists and is connected.",
    "pendingSummary": "Consolidate the active growth workflow, verify current data connections, and keep write actions guarded.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 746
  },
  {
    "name": "plantastichaven",
    "url": "https://github.com/douphealth/plantastichaven",
    "description": "Plantastic Haven website repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://plantastichaven.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 88,
    "doneSummary": "Website repository exists and is connected; the site has established search-demand pages worth optimizing.",
    "pendingSummary": "Prioritize pages already earning impressions, strengthen internal links/intent coverage, and finish trust/about improvements.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1406
  },
  {
    "name": "frenchyfab",
    "url": "https://github.com/douphealth/frenchyfab",
    "description": "FrenchyFab website repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://frenchyfab.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 87,
    "doneSummary": "Website repository exists and is connected; the care-plan app is a linked monetization asset.",
    "pendingSummary": "Restore verified WordPress write authentication before direct edits; complete editorial/trust pages and app-to-site monetization flow.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 436
  },
  {
    "name": "micegoneguide",
    "url": "https://github.com/douphealth/micegoneguide",
    "description": "Mice Gone Guide website repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://micegoneguide.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 86,
    "doneSummary": "Website repository exists and is connected; the elimination app is a linked monetization asset.",
    "pendingSummary": "Remove frozen/fragile Supabase dependency from the app path, verify Stripe flow, and connect the app cleanly to the site funnel.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1333
  },
  {
    "name": "gearuptogrow",
    "url": "https://github.com/douphealth/gearuptogrow",
    "description": "GearUpToGrow website repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://gearuptogrow.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 84,
    "doneSummary": "Website repository exists and is connected.",
    "pendingSummary": "Verify that this repo is the canonical production source, then define the highest-value growth/revenue work instead of parallel prototypes.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1035
  },
  {
    "name": "mystical-digits",
    "url": "https://github.com/douphealth/mystical-digits",
    "description": "Mystical Digits website repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://mysticaldigits.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 83,
    "doneSummary": "Website repository exists and is connected; the life-path app is a linked funnel asset.",
    "pendingSummary": "Tighten the website-to-life-path-app funnel, measurement, and monetization while improving organic/AI visibility.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 405
  },
  {
    "name": "claw-skills-hub",
    "url": "https://github.com/douphealth/claw-skills-hub",
    "description": "OpenClaw skills hub application/repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 82,
    "doneSummary": "OpenClaw skills-hub repository exists and is connected.",
    "pendingSummary": "Confirm canonical domain/deployment, tighten content/indexation architecture, and avoid duplicate skill-hub variants.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 5753
  },
  {
    "name": "frenchie-care-compass",
    "url": "https://github.com/douphealth/frenchie-care-compass",
    "description": "French Bulldog care-plan application connected to FrenchyFab.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://care-plan.frenchyfab.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 81,
    "doneSummary": "Application repository exists and has a live care-plan deployment.",
    "pendingSummary": "Verify Stripe/conversion tracking and canonical deployment; connect the app tightly to FrenchyFab content and CTAs.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 7073
  },
  {
    "name": "mice-solver-pro",
    "url": "https://github.com/douphealth/mice-solver-pro",
    "description": "Mice elimination application connected to Mice Gone Guide.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://elimination.micegoneguide.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 80,
    "doneSummary": "Application repository exists and has a live elimination-app deployment.",
    "pendingSummary": "Remove the frozen Supabase dependency, verify the paid flow, and validate production persistence.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 2355
  },
  {
    "name": "mystic-blueprint-maker",
    "url": "https://github.com/douphealth/mystic-blueprint-maker",
    "description": "Life-path / numerology application connected to Mystical Digits.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "https://life-path.mysticaldigits.com/",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 79,
    "doneSummary": "Application repository exists and has a live life-path deployment.",
    "pendingSummary": "Verify Stripe/conversion tracking and integrate the app into the highest-intent Mystical Digits pages.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1929
  },
  {
    "name": "runmatch-ai-buddy",
    "url": "https://github.com/douphealth/runmatch-ai-buddy",
    "description": "Running-shoe matching application family for GearUpToFit.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 78,
    "doneSummary": "Running-shoe matching app repository exists and is connected to the GearUpToFit app ecosystem.",
    "pendingSummary": "Confirm the canonical repo among duplicate variants, validate production routing, and connect conversion/affiliate measurement.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 2997
  },
  {
    "name": "nutri-match-wiz",
    "url": "https://github.com/douphealth/nutri-match-wiz",
    "description": "Nutrition matching application for the GearUpToFit ecosystem.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 77,
    "doneSummary": "Nutrition-matching app repository exists and is connected.",
    "pendingSummary": "Confirm canonical deployment, integrate into GearUpToFit, and add measurement/monetization before further feature expansion.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1229
  },
  {
    "name": "affiliatemarketingforsuccess-app",
    "url": "https://github.com/douphealth/affiliatemarketingforsuccess-app",
    "description": "Affiliatemarketingforsuccess App repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 75,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 156
  },
  {
    "name": "gearuptofit-body-recomp-os-guru",
    "url": "https://github.com/douphealth/gearuptofit-body-recomp-os-guru",
    "description": "Gearuptofit Body Recomp Os Guru repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 75,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 928
  },
  {
    "name": "gearuptofit-homepage",
    "url": "https://github.com/douphealth/gearuptofit-homepage",
    "description": "Gearuptofit Homepage repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 75,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 2181
  },
  {
    "name": "gearuptofit-runmatch-ai-buddy",
    "url": "https://github.com/douphealth/gearuptofit-runmatch-ai-buddy",
    "description": "Gearuptofit Runmatch Ai Buddy repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 75,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 2280
  },
  {
    "name": "openclaw-config",
    "url": "https://github.com/douphealth/openclaw-config",
    "description": "Openclaw Config repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 75,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 698
  },
  {
    "name": "openclaw-config-001",
    "url": "https://github.com/douphealth/openclaw-config-001",
    "description": "Openclaw Config 001 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 75,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1524
  },
  {
    "name": "image-alchemy-pro",
    "url": "https://github.com/douphealth/image-alchemy-pro",
    "description": "Image Alchemy application repository.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 74,
    "doneSummary": "Image Alchemy repository exists and is connected.",
    "pendingSummary": "Confirm current production deployment and revenue path, then consolidate any duplicate/experimental image-engine repos.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 462
  },
  {
    "name": "traffic-growth-engine",
    "url": "https://github.com/douphealth/traffic-growth-engine",
    "description": "Traffic Growth Engine repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 72,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 649
  },
  {
    "name": "surgical-seo-suite",
    "url": "https://github.com/douphealth/surgical-seo-suite",
    "description": "Surgical Seo Suite repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 70,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 379
  },
  {
    "name": "wise-scribe-engine",
    "url": "https://github.com/douphealth/wise-scribe-engine",
    "description": "Wise Scribe Engine repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 69,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1292
  },
  {
    "name": "wise-scribe-engine-d79d3d82",
    "url": "https://github.com/douphealth/wise-scribe-engine-d79d3d82",
    "description": "Wise Scribe Engine D79d3d82 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "active",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "high",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "high",
    "importance": 68,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 900
  },
  {
    "name": "amazon-product-box",
    "url": "https://github.com/douphealth/amazon-product-box",
    "description": "Amazon Product Box repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1034
  },
  {
    "name": "AmzWP",
    "url": "https://github.com/douphealth/AmzWP",
    "description": "AmzWP repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 2009
  },
  {
    "name": "basic-app-canvas",
    "url": "https://github.com/douphealth/basic-app-canvas",
    "description": "Basic App Canvas repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1612
  },
  {
    "name": "body-recomp-os-guru",
    "url": "https://github.com/douphealth/body-recomp-os-guru",
    "description": "Body Recomp Os Guru repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 777
  },
  {
    "name": "claw-compass",
    "url": "https://github.com/douphealth/claw-compass",
    "description": "Claw Compass repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 4600
  },
  {
    "name": "connect-your-code",
    "url": "https://github.com/douphealth/connect-your-code",
    "description": "Connect Your Code repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 129
  },
  {
    "name": "edit-ace-engine",
    "url": "https://github.com/douphealth/edit-ace-engine",
    "description": "Edit Ace Engine repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 435
  },
  {
    "name": "efficientgptprompts-emergency-home",
    "url": "https://github.com/douphealth/efficientgptprompts-emergency-home",
    "description": "Efficientgptprompts Emergency Home repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 84
  },
  {
    "name": "family-nutrition-os",
    "url": "https://github.com/douphealth/family-nutrition-os",
    "description": "Family Nutrition Os repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 61633
  },
  {
    "name": "form-beauty-studio",
    "url": "https://github.com/douphealth/form-beauty-studio",
    "description": "Form Beauty Studio repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1521
  },
  {
    "name": "gearup-flow-master",
    "url": "https://github.com/douphealth/gearup-flow-master",
    "description": "Gearup Flow Master repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 35458
  },
  {
    "name": "grow-stack-engine",
    "url": "https://github.com/douphealth/grow-stack-engine",
    "description": "Grow Stack Engine repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 511
  },
  {
    "name": "internal-link-automation",
    "url": "https://github.com/douphealth/internal-link-automation",
    "description": "Internal Link Automation repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 836
  },
  {
    "name": "Lovable2WP",
    "url": "https://github.com/douphealth/Lovable2WP",
    "description": "Lovable2WP repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 533
  },
  {
    "name": "neural-prompt-coach",
    "url": "https://github.com/douphealth/neural-prompt-coach",
    "description": "Neural Prompt Coach repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 813
  },
  {
    "name": "plantastic-haven-pro",
    "url": "https://github.com/douphealth/plantastic-haven-pro",
    "description": "Plantastic Haven Pro repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 857
  },
  {
    "name": "quiz-forge-ai-pro",
    "url": "https://github.com/douphealth/quiz-forge-ai-pro",
    "description": "Quiz Forge Ai Pro repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1403
  },
  {
    "name": "sublime-cherish-zenith",
    "url": "https://github.com/douphealth/sublime-cherish-zenith",
    "description": "Sublime Cherish Zenith repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 504
  },
  {
    "name": "wrist-wonderland-hub",
    "url": "https://github.com/douphealth/wrist-wonderland-hub",
    "description": "Wrist Wonderland Hub repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "stable",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "medium"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "medium",
    "importance": 50,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm current production use, deployment URL, owner, and next concrete milestone. Pause or archive the repo if it is no longer part of the active portfolio.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 3029
  },
  {
    "name": "ai-image-engine-001-lovable",
    "url": "https://github.com/douphealth/ai-image-engine-001-lovable",
    "description": "Ai Image Engine 001 Lovable repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 309
  },
  {
    "name": "ai-Image-Engine-lovable",
    "url": "https://github.com/douphealth/ai-Image-Engine-lovable",
    "description": "Ai Image Engine Lovable repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 640
  },
  {
    "name": "ai-image-engine-love",
    "url": "https://github.com/douphealth/ai-image-engine-love",
    "description": "Ai Image Engine Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 113
  },
  {
    "name": "ai-seo-orchestrator-001",
    "url": "https://github.com/douphealth/ai-seo-orchestrator-001",
    "description": "Ai Seo Orchestrator 001 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 265
  },
  {
    "name": "ai-seo-orchestrator-001-love",
    "url": "https://github.com/douphealth/ai-seo-orchestrator-001-love",
    "description": "Ai Seo Orchestrator 001 Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 149
  },
  {
    "name": "alexios-mission-control",
    "url": "https://github.com/douphealth/alexios-mission-control",
    "description": "Alexios Mission Control repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 1243
  },
  {
    "name": "alexios-mission-control-88d4c83b",
    "url": "https://github.com/douphealth/alexios-mission-control-88d4c83b",
    "description": "Alexios Mission Control 88d4c83b repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1010
  },
  {
    "name": "AmzWP-001",
    "url": "https://github.com/douphealth/AmzWP-001",
    "description": "AmzWP 001 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1011
  },
  {
    "name": "AmzWP-004",
    "url": "https://github.com/douphealth/AmzWP-004",
    "description": "AmzWP 004 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 623
  },
  {
    "name": "AmzWP-006-lovable",
    "url": "https://github.com/douphealth/AmzWP-006-lovable",
    "description": "AmzWP 006 Lovable repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 896
  },
  {
    "name": "AmzWP-006-love",
    "url": "https://github.com/douphealth/AmzWP-006-love",
    "description": "AmzWP 006 Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 914
  },
  {
    "name": "body-recomp-os-guru-7c1356da",
    "url": "https://github.com/douphealth/body-recomp-os-guru-7c1356da",
    "description": "Body Recomp Os Guru 7c1356da repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 984
  },
  {
    "name": "body-recomp-os-guru-cb7e904e",
    "url": "https://github.com/douphealth/body-recomp-os-guru-cb7e904e",
    "description": "Body Recomp Os Guru Cb7e904e repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 1006
  },
  {
    "name": "goal-forge-ai-love",
    "url": "https://github.com/douphealth/goal-forge-ai-love",
    "description": "Goal Forge Ai Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 101
  },
  {
    "name": "grow-stack-engine-4ae1d6eb",
    "url": "https://github.com/douphealth/grow-stack-engine-4ae1d6eb",
    "description": "Grow Stack Engine 4ae1d6eb repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 362
  },
  {
    "name": "grow-stack-engine-945df4aa",
    "url": "https://github.com/douphealth/grow-stack-engine-945df4aa",
    "description": "Grow Stack Engine 945df4aa repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 648
  },
  {
    "name": "growthscribe-os-1",
    "url": "https://github.com/douphealth/growthscribe-os-1",
    "description": "Growthscribe Os 1 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 982
  },
  {
    "name": "internal-link-auto-love",
    "url": "https://github.com/douphealth/internal-link-auto-love",
    "description": "Internal Link Auto Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 70
  },
  {
    "name": "mission-control-center",
    "url": "https://github.com/douphealth/mission-control-center",
    "description": "Mission Control Center repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 733
  },
  {
    "name": "mission-control-center-2d32d572",
    "url": "https://github.com/douphealth/mission-control-center-2d32d572",
    "description": "Mission Control Center 2d32d572 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1074
  },
  {
    "name": "my-new-mission-control-center",
    "url": "https://github.com/douphealth/my-new-mission-control-center",
    "description": "My New Mission Control Center repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1265
  },
  {
    "name": "newAmzWP-006-lovable",
    "url": "https://github.com/douphealth/newAmzWP-006-lovable",
    "description": "NewAmzWP 006 Lovable repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 448
  },
  {
    "name": "nutri-match-wiz-1eb55346",
    "url": "https://github.com/douphealth/nutri-match-wiz-1eb55346",
    "description": "Nutri Match Wiz 1eb55346 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 607
  },
  {
    "name": "plantastic-haven-pro-8e23ae56",
    "url": "https://github.com/douphealth/plantastic-haven-pro-8e23ae56",
    "description": "Plantastic Haven Pro 8e23ae56 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 1727
  },
  {
    "name": "runmatch-ai-buddy-1282c193",
    "url": "https://github.com/douphealth/runmatch-ai-buddy-1282c193",
    "description": "Runmatch Ai Buddy 1282c193 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 112577
  },
  {
    "name": "runmatch-ai-buddy-c4c42964",
    "url": "https://github.com/douphealth/runmatch-ai-buddy-c4c42964",
    "description": "Runmatch Ai Buddy C4c42964 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 112716
  },
  {
    "name": "social-media-co-pilot-love",
    "url": "https://github.com/douphealth/social-media-co-pilot-love",
    "description": "Social Media Co Pilot Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 60
  },
  {
    "name": "sota-god-mode-003-love",
    "url": "https://github.com/douphealth/sota-god-mode-003-love",
    "description": "Sota God Mode 003 Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 2661
  },
  {
    "name": "sota-god-mode-014-love",
    "url": "https://github.com/douphealth/sota-god-mode-014-love",
    "description": "Sota God Mode 014 Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is codex/enhance-design-of-wordpress-content-app.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "codex/enhance-design-of-wordpress-content-app",
    "repoSizeKb": 2077
  },
  {
    "name": "sublime-cherish-zenith-4d8c3c83",
    "url": "https://github.com/douphealth/sublime-cherish-zenith-4d8c3c83",
    "description": "Sublime Cherish Zenith 4d8c3c83 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 680
  },
  {
    "name": "wp-html-snippet-love",
    "url": "https://github.com/douphealth/wp-html-snippet-love",
    "description": "Wp Html Snippet Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 59
  },
  {
    "name": "wp-quiz-forge-love",
    "url": "https://github.com/douphealth/wp-quiz-forge-love",
    "description": "Wp Quiz Forge Love repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "public",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (public); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "public",
    "defaultBranch": "main",
    "repoSizeKb": 80
  },
  {
    "name": "wrist-wonderland-hub-460cce97",
    "url": "https://github.com/douphealth/wrist-wonderland-hub-460cce97",
    "description": "Wrist Wonderland Hub 460cce97 repository tracked in Mission Control.",
    "language": "Unknown",
    "stars": 0,
    "forks": 0,
    "status": "paused",
    "demoUrl": "",
    "progress": 0,
    "topics": [
      "github",
      "private",
      "low",
      "canonical-review"
    ],
    "lastUpdated": "2026-09-28",
    "priority": "low",
    "importance": 25,
    "doneSummary": "Repository is connected in GitHub (private); default branch is main.",
    "pendingSummary": "Confirm whether this is the canonical repository. If superseded, consolidate useful changes into the canonical repo and archive/stop using the duplicate.",
    "visibility": "private",
    "defaultBranch": "main",
    "repoSizeKb": 2983
  }
];
