import { useEffect, useMemo, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { CheckCircle2, Clock3, Mail, RefreshCw, Send, ShieldCheck, TriangleAlert } from "lucide-react";
import { toast } from "sonner";
import { db } from "@/lib/db";
import { getCloudUserId } from "@/lib/cloudSync";
import { getDailyDigestHealth, syncDailyDigestSnapshot } from "@/lib/dailyDigestSync";
const HOURS=Array.from({length:24},(_,h)=>h); const hourLabel=(h:number)=>new Date(2020,0,1,h).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"});
export default function DailyEmailSettings(){
 const s=useLiveQuery(()=>db.settings.get("default"),[]),[busy,setBusy]=useState<"sync"|"send"|null>(null),[health,setHealth]=useState<any>(null);
 const tz=useMemo(()=>Intl.DateTimeFormat().resolvedOptions().timeZone||"UTC",[]),enabled=s?.digestEmailEnabled!==false,sendHour=Number.isFinite(s?.digestEmailHour)?Number(s?.digestEmailHour):8,chosenTz=s?.digestEmailTimezone||tz,recipient=getCloudUserId();
 const refresh=async()=>{try{setHealth(await getDailyDigestHealth())}catch{setHealth({ok:false,storageConfigured:false,emailConfigured:false,schedulerReady:false})}};
 useEffect(()=>{void refresh()},[]); useEffect(()=>{if(!s||s.digestEmailTimezone)return;void db.settings.update("default",{digestEmailTimezone:tz,digestEmailHour:s.digestEmailHour??8,digestEmailEnabled:s.digestEmailEnabled??true})},[s,tz]);
 const update=async(changes:any)=>{await db.settings.update("default",changes);void syncDailyDigestSnapshot({silent:true})};
 const syncNow=async(sendNow=false)=>{setBusy(sendNow?"send":"sync");try{const r=await syncDailyDigestSnapshot({sendNow});if(!r.ok)throw new Error(r.error||"Daily briefing sync failed");toast.success(sendNow?"Daily briefing email sent":"Daily briefing snapshot synced",r.email?{description:`Recipient: ${r.email}`}:undefined);await refresh()}catch(e){toast.error(sendNow?"Email was not sent":"Briefing was not synced",{description:e instanceof Error?e.message:String(e)})}finally{setBusy(null)}};
 const ready=health?.storageConfigured&&health?.emailConfigured&&health?.schedulerReady;
 return <div className="space-y-4"><section className="overflow-hidden rounded-3xl border border-border/50 bg-card shadow-[0_24px_70px_-50px_hsl(var(--foreground)/0.45)]">
 <div className="relative overflow-hidden border-b border-border/40 bg-gradient-to-br from-primary/10 via-card to-sky-500/5 p-5 sm:p-6"><div className="relative flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[0.17em] text-primary"><Mail size={14}/>Daily executive briefing</div><h2 className="mt-2 font-display text-2xl font-black tracking-[-0.04em]">Start every day knowing exactly what needs action.</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">One concise email prioritizes overdue work, today&apos;s commitments, finance, reminders, SEO problems, failed validations, sync failures, website incidents, repository next steps, and unfinished builds.</p></div>
 <button type="button" role="switch" aria-checked={enabled} onClick={()=>void update({digestEmailEnabled:!enabled})} className={`relative h-8 w-14 shrink-0 rounded-full border ${enabled?"border-primary/30 bg-primary":"border-border/60 bg-secondary"}`}><span className={`absolute top-1 h-6 w-6 rounded-full bg-white shadow-sm transition-all ${enabled?"left-7":"left-1"}`}/></button></div></div>
 <div className="grid gap-3 p-4 sm:grid-cols-2 sm:p-5"><div className="rounded-2xl border border-border/40 bg-background/45 p-4"><div className="flex items-center gap-2 text-xs font-bold"><Clock3 size={14} className="text-primary"/>Delivery time</div><div className="mt-3 grid grid-cols-[110px_1fr] gap-2"><select value={sendHour} onChange={e=>void update({digestEmailHour:Number(e.target.value)})} className="rounded-xl border border-border/50 bg-card px-3 py-2 text-sm font-semibold">{HOURS.map(h=><option key={h} value={h}>{hourLabel(h)}</option>)}</select><input value={chosenTz} onChange={e=>void update({digestEmailTimezone:e.target.value.trim()||tz})} className="min-w-0 rounded-xl border border-border/50 bg-card px-3 py-2 text-xs"/></div><p className="mt-2 text-[10px] text-muted-foreground">Scheduler checks hourly and sends once per local day.</p></div>
 <div className="rounded-2xl border border-border/40 bg-background/45 p-4"><div className="flex items-center gap-2 text-xs font-bold"><ShieldCheck size={14} className="text-primary"/>Verified recipient</div><p className="mt-3 truncate text-sm font-semibold">{recipient||"Connect Google to verify the recipient"}</p><p className="mt-2 text-[10px] leading-relaxed text-muted-foreground">Passwords, credential-vault contents, API keys, and note bodies are never included in the server snapshot.</p></div></div>
 <div className="grid gap-2 border-t border-border/40 p-4 sm:grid-cols-3 sm:p-5">{[["Storage",health?.storageConfigured],["Mailflare delivery",health?.mailflareConfigured||health?.resendConfigured],["Daily scheduler",health?.schedulerReady]].map(([label,ok])=><div key={String(label)} className="flex items-center gap-2 rounded-xl border border-border/40 bg-secondary/30 px-3 py-2">{ok?<CheckCircle2 size={14} className="text-emerald-500"/>:<TriangleAlert size={14} className="text-amber-500"/>}<span className="text-[11px] font-semibold">{label}</span><span className="ml-auto text-[9px] font-bold uppercase text-muted-foreground">{ok?"ready":"setup"}</span></div>)}</div>
 <div className="px-4 pb-4 sm:px-5 sm:pb-5"><div className="rounded-2xl border border-border/40 bg-background/45 p-3 text-[10px] leading-relaxed text-muted-foreground">{health?.mailflareConfigured?"Mailflare is the active primary transport. Sent-mail history and domain identity stay in your Cloudflare-hosted mail stack.":health?.resendConfigured?"Direct Resend fallback is active. Add Mailflare configuration to make Mailflare the primary transport.":"Connect Mailflare (preferred) or Resend before enabling automated delivery."}</div></div>
 <div className="flex flex-wrap items-center gap-2 border-t border-border/40 bg-secondary/15 p-4 sm:p-5"><button onClick={()=>void syncNow(false)} disabled={busy!==null} className="inline-flex min-h-10 items-center gap-2 rounded-xl border border-border/50 bg-card px-4 text-xs font-bold"><RefreshCw size={13} className={busy==="sync"?"animate-spin":""}/>Sync briefing now</button><button onClick={()=>void syncNow(true)} disabled={busy!==null||!ready} className="inline-flex min-h-10 items-center gap-2 rounded-xl bg-primary px-4 text-xs font-bold text-primary-foreground disabled:opacity-40"><Send size={13}/>Send test email</button><button onClick={()=>void refresh()} className="ml-auto text-[10px] font-semibold text-muted-foreground">Recheck backend</button></div></section></div>
}
