/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceTranscribeRouteImport } from './routes/api/voice/transcribe'
import { Route as ApiPublicDigestRouteImport } from './routes/api/public/digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceTranscribeRoute = ApiVoiceTranscribeRouteImport.update({
  id: '/api/voice/transcribe',
  path: '/api/voice/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDigestRoute = ApiPublicDigestRouteImport.update({
  id: '/api/public/digest',
  path: '/api/public/digest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/digest': typeof ApiPublicDigestRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/digest': typeof ApiPublicDigestRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/digest': typeof ApiPublicDigestRoute
  '/api/voice/transcribe': typeof ApiVoiceTranscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/digest' | '/api/voice/transcribe'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/digest' | '/api/voice/transcribe'
  id: '__root__' | '/' | '/api/public/digest' | '/api/voice/transcribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicDigestRoute: typeof ApiPublicDigestRoute
  ApiVoiceTranscribeRoute: typeof ApiVoiceTranscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/transcribe': {
      id: '/api/voice/transcribe'
      path: '/api/voice/transcribe'
      fullPath: '/api/voice/transcribe'
      preLoaderRoute: typeof ApiVoiceTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/digest': {
      id: '/api/public/digest'
      path: '/api/public/digest'
      fullPath: '/api/public/digest'
      preLoaderRoute: typeof ApiPublicDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicDigestRoute: ApiPublicDigestRoute,
  ApiVoiceTranscribeRoute: ApiVoiceTranscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
